site_name: map-uk
repo_url: https://github.com/jap546/map-uk
site_url: https://jap546.github.io/map-uk
site_description: Quickly create maps of the UK in Python
site_author: Jordan Pinder
edit_uri: edit/main/docs/
repo_name: jap546/map-uk
copyright: Maintained by Jordan Pinder.

nav:
  - Home: index.md
  - Usage: usage.md
  - API reference: modules.md
  - Contributing: CONTRIBUTING.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jap546/map-uk
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/map-uk

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
